enum APIResponseStatus {
    ERROR = -1,
    SUCCESS,
    INVALID_CREDENTIALS,
    INVALID_TOKEN,
    DATA_NOT_FOUND,
    INVALID_PERMISSIONS,
    INVALID_REQUEST_BODY,
    INVALID_REQUEST_QUERY
}

export default APIResponseStatus;